name = "Pop"

[light.variables]
accent_color = "rgb(225,160,22)"
accent_bg_color = "rgb(255,173,0)"
accent_fg_color = "rgb(48,48,48)"
destructive_color = "#c01c28"
destructive_bg_color = "#e01b24"
destructive_fg_color = "#ffffff"
success_color = "#26a269"
success_bg_color = "#2ec27e"
success_fg_color = "#ffffff"
warning_color = "#ae7b03"
warning_bg_color = "#e5a50a"
warning_fg_color = "rgba(0, 0, 0, 0.8)"
error_color = "#c01c28"
error_bg_color = "#e01b24"
error_fg_color = "#ffffff"
window_bg_color = "#fafafa"
window_fg_color = "rgba(0, 0, 0, 0.8)"
view_bg_color = "#ffffff"
view_fg_color = "#000000"
headerbar_bg_color = "rgb(87,79,74)"
headerbar_fg_color = "rgb(255,255,255)"
headerbar_border_color = "rgba(0, 0, 0, 0.8)"
headerbar_backdrop_color = "rgb(87,79,74)"
headerbar_shade_color = "rgba(0, 0, 0, 0.07)"
card_bg_color = "#ffffff"
card_fg_color = "rgba(0, 0, 0, 0.8)"
card_shade_color = "rgba(0, 0, 0, 0.07)"
dialog_bg_color = "#fafafa"
dialog_fg_color = "rgba(0, 0, 0, 0.8)"
popover_bg_color = "#ffffff"
popover_fg_color = "rgba(0, 0, 0, 0.8)"
shade_color = "rgba(0,0,0,0.07)"
scrollbar_outline_color = "rgb(255,255,255)"

[light.palette.blue]
1 = "#99c1f1"
2 = "#62a0ea"
3 = "#3584e4"
4 = "#1c71d8"
5 = "#1a5fb4"

[light.palette.green]
1 = "#8ff0a4"
2 = "#57e389"
3 = "#33d17a"
4 = "#2ec27e"
5 = "#26a269"

[light.palette.yellow]
1 = "#f9f06b"
2 = "#f8e45c"
3 = "#f6d32d"
4 = "#f5c211"
5 = "#e5a50a"

[light.palette.orange]
1 = "#ffbe6f"
2 = "#ffa348"
3 = "#ff7800"
4 = "#e66100"
5 = "#c64600"

[light.palette.red]
1 = "#f66151"
2 = "#ed333b"
3 = "#e01b24"
4 = "#c01c28"
5 = "#a51d2d"

[light.palette.purple]
1 = "#dc8add"
2 = "#c061cb"
3 = "#9141ac"
4 = "#813d9c"
5 = "#613583"

[light.palette.brown]
1 = "#cdab8f"
2 = "#b5835a"
3 = "#986a44"
4 = "#865e3c"
5 = "#63452c"

[light.palette.light]
1 = "#ffffff"
2 = "#f6f5f4"
3 = "#deddda"
4 = "#c0bfbc"
5 = "#9a9996"

[light.palette.dark]
1 = "#77767b"
2 = "#5e5c64"
3 = "#3d3846"
4 = "#241f31"
5 = "#000000"

[light.custom_css]
gtk4 = """
windowcontrols image {
    background-color: transparent;
}   
/* If you want to keep the circles when you hover: */
windowcontrols image:hover {
    background-color: alpha(@headerbar_fg_color, 0.16);
}
/* When the buttons are pushed down: */
windowcontrols image:active {
    background-color: alpha(@headerbar_fg_color, 0.10);
}
headerbar windowcontrols button.close image {
    background-color: #f28c2a;
}
headerbar windowcontrols button.close image:hover {
   background-color: alpha(@headerbar_fg_color, 0.16);
}
headerbar windowcontrols button.close image:active {
    background-color: alpha(@headerbar_fg_color, 0.10);
}
headerbar:backdrop windowcontrols button.close image {
    background-color: transparent;
}
headerbar:backdrop windowcontrols button.close image:hover {
    background-color: alpha(@headerbar_fg_color, 0.10);
}
switch slider {
    background-color: #f6f6f6;
}
switch {
    background-color: #a9a9a9;
}
switch:checked {
    background-color: #ffad00;
}
checkbutton check:checked{
    color: #363636;
    background-color:#ffad00;
}
scale highlight{
    background-color: #48b9c7;
}
scale slider{
    background-color: #48b9c7;
}
list row.activatable:selected{
    color: @dark_5;
    background-color: #48b9c7;
}
window{
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
    border-top-left-radius: 5px;
    border-top-right-radius: 5px;
}"""
gtk3 = ""
